server:
  port: 3000

eureka:
  instance:
    hostname: ${hostname}
#    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${eurekaUrl}

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - 'http://joyfarm.xyz'
              - 'http://www.joyfarm.xyz'
              - 'http://joyfarm.xyz:4000'
              - 'http://www.joyfarm.xyz:4000'
            allowCredentials: true # 요청시 인증 정보 전송 허가
            allowedHeaders: '*'
            allowedMethods: '*'
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true

      routes:
        - id: front-service
          uri: lb://front-service
          predicates:
            - Path=/app/**
          filters:
            - RewritePath=/app/?(?<path>.*),/$\{path}

        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
          filters:
            - RewritePath=/admin/?(?<path>.*),/$\{path}

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway